const FIELDS_TYPE_VALUE_IS_ARRAY = ['CHECK_BOX', 'MULTI_SELECT', 'ATTACHMENT', 'USER_SELECT', 'TABLE'];

const GET_RECORDS_LIMITATION = 500;

export {
  GET_RECORDS_LIMITATION,
  FIELDS_TYPE_VALUE_IS_ARRAY
};