const FIELD_TYPE = {
  SUBTABLE: 'SUBTABLE'
};

const REQUESTING_EXCEPT_FIELDS = [
  'CREATOR',
  'MODIFIER',
  'RECORD_NUMBER',
  'CREATED_TIME',
  'CATEGORY',
  'UPDATED_TIME',
  'STATUS',
  'STATUS_ASSIGNEE',
  '__REVISION__',
  '__ID__'
];

export {
  FIELD_TYPE,
  REQUESTING_EXCEPT_FIELDS
};